#!/usr/bin/env python
"""dag_codegen — vendor the causal DAG into `src/state_graph_data.py`.

`tools/phases/dag.py` holds the causal graph (metrics, edges, KIND, CONTROLS, EDGE_META) but
it lives under `tools/`, and `package.py` bundles `src/` alone -- so the agent cannot import
it. This copies the graph in as literals, the same pattern as `priors_codegen` and
`bench_codegen`.

Usage
-----
  PYTHONPATH=. python -m tools.phases.dag_codegen
"""
from __future__ import annotations
import argparse, sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

HEADER = '''"""state_graph_data — the causal DAG, vendored. GENERATED by `tools/phases/dag_codegen.py`.

Do not edit by hand; edit `tools/phases/dag.py` and regenerate. The graph says which metric
CAUSES which, which nodes are `controllable` vs `latent`, and which source file owns each
node. `src/state_graph.py` evaluates it on the live state to find the ROOT of a deficiency.
"""
from __future__ import annotations

# metric -> {label, phase, src, agg, target_key, better, tol, owner, desc, descriptive}
METRICS = {metrics}

# (cause, effect, mechanism)
EDGES = {edges}

# metric -> 'controllable' | 'latent'
KIND = {kind}

# metric -> the source that owns the fix
CONTROLS = {controls}

# (cause, effect) -> (lag_days, measured evidence)
EDGE_META = {edge_meta}
'''


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="src/state_graph_data.py")
    a = ap.parse_args(argv)
    from tools.phases import dag
    body = (HEADER
            .replace("{metrics}", repr(dag.METRICS))
            .replace("{edges}", repr(dag.EDGES))
            .replace("{kind}", repr(dag.KIND))
            .replace("{controls}", repr(dag.CONTROLS))
            .replace("{edge_meta}", repr(dag.EDGE_META)))
    Path(a.out).write_text(body)
    print(f"wrote {a.out} ({len(body)} bytes): {len(dag.METRICS)} metrics, "
          f"{len(dag.EDGES)} edges, {len(dag.KIND)} kinds")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
