#!/usr/bin/env python
"""priors_codegen — turn the measured prior table into a self-contained `src/priors.py`.

`docs/boey_priors.json` is the evidence; `src/priors.py` is what the agent ships. The
submission bundle is a single file built from `src/` (`package.py`), so the agent cannot
read a JSON at runtime -- the tables have to be literals. Generating the module keeps the
two in step and keeps `src/` free of any file I/O.

Usage
-----
  PYTHONPATH=. python -m tools.phases.boey_priors --all --workers 8   # refresh evidence
  PYTHONPATH=. python -m tools.phases.priors_codegen                  # refresh src/priors.py
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

HEADER = '''"""priors — the reference's measured policy, as the planner's starting point.

GENERATED by `tools/phases/priors_codegen.py` from `docs/boey_priors.json`; do not edit by
hand. Evidence: {games} of Boey's episodes, d{d0}-d{d1}.

These are TARGETS, not laws. `src/plan.py` starts from them and may leave one only inside
`tolerance()` and only with a priced reason from `src/value.py`. Each table is the median
across episodes (with p10/p90 where the spread is wide enough to matter), so a single game
may legitimately sit off-target.

Why they are priors rather than constraints: the reference is running the same optimisation
we are, so his trajectory is a solved example. Starting from it means every deviation is a
claim we have to justify in dollars, instead of re-deriving the whole policy from scratch.
"""
from __future__ import annotations

# ---- how much cash to hold (median bank at end of day) ----------------------
CASH = {cash}
CASH_P10 = {cash_p10}
CASH_P90 = {cash_p90}

# ---- land: cumulative quadrants bought by end of day -----------------------
LAND_CUM = {land_cum}

# ---- herd: total animals, and per species, split by YARN unlocked ----------
TOTAL_ANIMALS = {total_animals}
SPECIES_ALL = {species_all}
SPECIES_YARN = {species_yarn}
SPECIES_NOYARN = {species_noyarn}
# shop -> (species, median WITH the shop, median WITHOUT) -- the herd response
HERD_BY_SHOP = {herd_by_shop}

# ---- crops: tiles per day --------------------------------------------------
CROPS = {crops}

# ---- labour and fertiliser -------------------------------------------------
HIRES = {hires}
FERT = {fert}
FERT_GATE_ANIMALS = {fert_gate}

# ---- shed hold levels (median units kept), for the sell/hold decision ------
SHED_HOLD = {shed_hold}


def _at(table, day, default=0.0):
    """Value for `day`, else the nearest earlier day, else `default`."""
    if not table:
        return default
    if day in table:
        return table[day]
    earlier = [d for d in table if d <= day]
    if earlier:
        return table[max(earlier)]
    return table[min(table)]


def cash_target(day):
    """Median bank the reference holds at the end of `day`."""
    return _at(CASH, day, 0.0)


def cash_band(day):
    """(p10, p90) of his bank -- the range a plan may sit in without a priced reason."""
    return _at(CASH_P10, day, 0.0), _at(CASH_P90, day, 0.0)


def land_target(day):
    """Quadrants he has bought by the end of `day` (1 = NW only)."""
    return int(_at(LAND_CUM, day, 1))


def herd_target(day, shops=()):
    """Expected animals by species at `day`, given whether YARN has unlocked.

    The yarn/no-yarn tables ARE the conditional target -- the split already contains the
    shop response, so nothing else is applied here. (An earlier version also multiplied by
    `HERD_BY_SHOP`'s with/without ratio and produced SHEEP 45 at d14: that table is a
    marginal comparison over all days, not a factor to compound on top of the split.)
    """
    src = SPECIES_YARN if any("YARN" in str(s) for s in shops) else SPECIES_NOYARN
    return {sp: _at(table, day, 0.0) for sp, table in src.items()}


def herd_shop_effect(shop, species):
    """EVIDENCE ONLY: median count of `species` on days with `shop` vs without.

    Returned as (with, without) so the planner can weigh a shop-driven herd shift itself
    rather than have it silently folded into a target.
    """
    info = HERD_BY_SHOP.get(str(shop))
    if not info or info[0] != species:
        return None
    return info[1], info[2]


def total_animals(day):
    return _at(TOTAL_ANIMALS, day, 0.0)


def crop_target(day, crop_key):
    """Median tiles of `crop_key` (wheat_tiles / straw_tiles / planted / empty)."""
    return _at((CROPS.get(crop_key) or {}), day, 0.0)


def hire_target(day):
    """HIRE orders he places on `day` (the crew is wiped nightly)."""
    return int(round(_at(HIRES, day, 0.0)))


def fert_target(day):
    """FERTILIZE ops he performs on `day`; ramps once the herd matures."""
    return int(round(_at(FERT, day, 0.0)))


def shed_hold(item, day):
    """Median units of `item` he keeps in the shed -- the sell/hold reference point."""
    return _at((SHED_HOLD.get(item) or {}), day, 0.0)


def tolerance(kind):
    """How far a plan may sit from a target before it needs a priced justification."""
    return dict(cash=0.0, land=0, animals=2.0, crops=4.0, hires=2,
                fert=4).get(kind, 0.0)
'''


def _ints(d):
    return {int(k): v for k, v in d.items()}


def _ints_round(d, nd=1):
    return {int(k): round(float(v), nd) for k, v in d.items()}


def _series1(d, key, nd=1):
    return {int(k): round(float(v.get(key, 0)), nd) for k, v in d.items()}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--json", default="docs/boey_priors.json")
    ap.add_argument("--out", default="src/priors.py")
    a = ap.parse_args(argv)
    m = json.load(open(a.json))
    fields = dict(
        games=m["games"], d0=m["days"][0], d1=m["days"][1],
        cash={int(k): round(v["median"]) for k, v in m["cash_hold"].items()},
        cash_p10={int(k): round(v["p10"]) for k, v in m["cash_hold"].items()},
        cash_p90={int(k): round(v["p90"]) for k, v in m["cash_hold"].items()},
        land_cum=_ints_round(m["land"]["cum_buys_by_day"], 0),
        total_animals=_series1(m["total_animals"], "median", 0),
        species_all={s: _ints_round(t) for s, t in m["herd_all"].items()},
        species_yarn={s: _ints_round(t) for s, t in m["herd_yarn"].items()},
        species_noyarn={s: _ints_round(t) for s, t in m["herd_noyarn"].items()},
        herd_by_shop={k: (v["species"], v["median_with"],
                          v["median_without"] or 0)
                      for k, v in m["herd_by_shop"].items()},
        crops={k: _series1(v, "median", 0) for k, v in m["crops"].items()},
        hires=_ints_round(m["hires"], 0),
        fert=_ints_round(m["fert"], 0),
        fert_gate=(m["fert_gate"]["animals_median_when_fert"],
                   m["fert_gate"]["animals_median_when_no_fert"]),
        shed_hold={k: _ints_round(v, 0) for k, v in m["shed_hold"].items()},
    )
    # Plain token replacement, not `str.format`: the generated module contains its own
    # dict literals, and format() would try to interpret every brace as a field.
    body = HEADER
    for k, v in fields.items():
        body = body.replace("{" + k + "}", str(v))
    Path(a.out).write_text(body)
    print(f"wrote {a.out}  ({len(body)} bytes) from {a.json} "
          f"[{m['games']} games, d{m['days'][0]}-{m['days'][1]}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
