"""graph_weights -- node->op weights LEARNED from the reference replays.

GENERATED by `tools/phases/fit_graph.py --windows`; evidence docs/graph_weights.json.

Measured held-out R2 (split BY GAME, 60 replays / 1,800 game-days):
  global weights  median +0.224
  FIVE windows    median +0.486   <-- this table
  30-day          median +0.438   (2.8 obs/param, overfits -- finer is NOT better)
"""
from __future__ import annotations

WINDOWS = ((0, 5), (6, 10), (11, 17), (18, 23), (24, 29))

def win_of(day):
    for i, (a_, b_) in enumerate(WINDOWS):
        if a_ <= day <= b_:
            return i
    return len(WINDOWS) - 1

W = {
    'WATER': {
        0: {'animals': 13.0066, 'output_per_day': 3.0516, 'planted': 21.6616},
        1: {'empty': 1.6163, 'output_per_day': 0.5926, 'shed': 0.1024, 'structures': 3.8657},
        2: {'empty': 0.4762, 'revenue_per_day': 1.5144, 'unfed': 0.1716},
        3: {'animals': 5.4532, 'empty': 0.1741, 'money': 2.6091, 'revenue_per_day': 2.4047, 'unfed': 1.5626},
        4: {'output_per_day': 27.4806, 'revenue_per_day': 11.4558, 'unfed': 1.081},
    },
    'FERTILIZE': {
        0: {'empty': 0.0277, 'structures': 0.0539},
        1: {'empty': 0.0626, 'money': 0.1453, 'output_per_day': 1.3336, 'structures': 0.1822, 'unfed': 0.0754},
        2: {'output_per_day': 0.9268, 'revenue_per_day': 1.4177, 'unfed': 0.5864},
        3: {'unfed': 0.8111},
        4: {'output_per_day': 5.2099, 'revenue_per_day': 1.9713, 'unfed': 2.4338},
    },
    'HARVEST': {
        0: {'planted': 16.3515, 'revenue_per_day': 2.0453, 'shed': 2.1628, 'structures': 0.4853},
        1: {'empty': 0.0999, 'money': 0.1221, 'output_per_day': 16.9483},
        2: {'output_per_day': 3.7277, 'revenue_per_day': 0.7284, 'unfed': 0.8785},
        3: {'revenue_per_day': 2.8119},
        4: {'revenue_per_day': 0.0441, 'weeds': 0.9613},
    },
    'PLANT': {
        0: {'money': 1.0639},
        1: {'empty': 2.5485, 'money': 3.0318, 'revenue_per_day': 3.2183, 'shed': 0.5086},
        2: {'empty': 1.4323, 'revenue_per_day': 0.0039},
        3: {'unfed': 0.4954},
        4: {'output_per_day': 19.8776, 'revenue_per_day': 1.4242, 'unfed': 0.6604},
    },
    'FEED': {
        0: {'money': 0.7574, 'planted': 2.9844, 'revenue_per_day': 2.9434, 'unfed': 0.2913},
        1: {'money': 3.1128, 'output_per_day': 6.0618, 'shed': 0.2173, 'unfed': 0.306},
        2: {'revenue_per_day': 0.4547},
        3: {'planted': 14.4774},
        4: {'output_per_day': 9.514, 'planted': 11.0348, 'revenue_per_day': 4.9155},
    },
    'CARE': {
        0: {'money': 0.4443, 'planted': 2.0264, 'revenue_per_day': 3.0662, 'shed': 0.969, 'unfed': 0.1815},
        1: {'money': 2.6429, 'output_per_day': 4.6273, 'unfed': 0.2133},
        2: {'revenue_per_day': 0.8995},
        3: {'planted': 1.2792, 'revenue_per_day': 0.0923},
        4: {'output_per_day': 13.7089, 'revenue_per_day': 5.0627},
    },
    'COLLECT_FERTILIZER': {
        0: {'money': 0.4374, 'planted': 1.088, 'revenue_per_day': 5.8326, 'shed': 6.2066, 'unfed': 0.1501},
        1: {'money': 2.7029, 'output_per_day': 5.8585, 'shed': 0.6067, 'unfed': 0.5122},
        2: {'revenue_per_day': 0.204, 'unfed': 0.0206},
        3: {'revenue_per_day': 0.7024, 'unfed': 0.1465},
        4: {'empty': 0.0523, 'output_per_day': 4.0151, 'revenue_per_day': 1.9624, 'unfed': 0.5179},
    },
    'DIG': {
        0: {'empty': 0.0076},
        1: {'animals': 0.2962, 'money': 0.0329, 'revenue_per_day': 0.0981, 'shed': 0.0203, 'weeds': 0.078},
        2: {'empty': 0.0877, 'revenue_per_day': 0.112, 'structures': 0.2829, 'unfed': 0.0798, 'weeds': 0.1714},
        3: {'unfed': 0.4018},
        4: {'animals': 0.9919, 'empty': 0.0835, 'output_per_day': 0.7662, 'revenue_per_day': 1.4677, 'unfed': 0.152},
    },
    'PLACE': {
        0: {'money': 0.9297},
        1: {'output_per_day': 1.6336, 'quadrants': 10.2025, 'revenue_per_day': 2.8288},
        2: {'revenue_per_day': 0.7065},
        3: {'empty': 0.216, 'output_per_day': 0.1053, 'planted': 0.0238, 'revenue_per_day': 0.1534},
    },
    'BUILD_PASTURE': {
        0: {'money': 0.7987},
        1: {'empty': 0.9706, 'labour': 0.883, 'planted': 0.1538, 'revenue_per_day': 0.6439},
        2: {'empty': 0.0009, 'money': 0.451, 'planted': 0.6918, 'revenue_per_day': 0.0772},
        3: {'output_per_day': 0.0732, 'planted': 0.2876},
        4: {'money': 0.0107, 'revenue_per_day': 0.011, 'weeds': 0.0024},
    },
    'BUILD_COOP': {
        0: {'planted': 2.936, 'revenue_per_day': 0.1551},
        1: {'money': 0.6444, 'output_per_day': 0.7086, 'quadrants': 0.3124},
        2: {'empty': 0.0653, 'money': 0.0181, 'unfed': 0.011},
        3: {'output_per_day': 0.0009, 'unfed': 0.0001},
        4: {'money': 0.0442, 'revenue_per_day': 0.0583},
    },
}

def weights_for(op, day):
    """The learned node->op weights for the window containing `day`."""
    return W.get(op, {}).get(win_of(day), {})
